version: '3'

services:
  users:
    restart: always
    build: ./users
    container_name: users-svc
    ports:
      - "3000:8080"
    command: npm run serve

  orders:
    restart: always
    build: ./orders
    container_name: orders-svc
    ports:
      - "3001:8080"
    command: npm run serve

  catalog:
    restart: always
    build: ./catalog
    container_name: catalog-svc
    ports:
      - "3002:8080"
    command: npm run serve

  # zookeeper:
  #   image: confluentinc/cp-zookeeper:latest
  #   hostname: zookeeper
  #   ports:
  #     - "2181:2181"
  #   environment:
  #     ZOO_MY_ID: 1
  #     ZOO_PORT: 2181
  #     ZOO_SERVERS: server.1=zookeeper:2888:3888

  # kafka:
  #   image: confluentinc/cp-kafka:latest
  #   hostname: kafka1
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
