version: '3'

services:
  users:
    restart: always
    build: ./users
    container_name: users-svc
    ports:
      - "3000:8080"
    command: npm run serve

  orders:
    restart: always
    build: ./orders
    container_name: orders-svc
    ports:
      - "3001:8080"
    command: npm run serve

  catalog:
    restart: always
    build: ./catalog
    container_name: catalog-svc
    ports:
      - "3002:8080"
    command: npm run serve
